---

- name: Update Packages
  sudo: yes
  apt:
    update_cache: yes
    upgrade: safe

- name: Install common system packages
  sudo: yes
  apt:
    pkg: "{{ common_system_packages }}"
    state: latest

- name: Install required system packages
  sudo: yes
  apt:
    pkg: "{{ required_system_packages }}"
    state: latest
